# Generated by Django 3.0.8 on 2020-07-15 13:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lovematch', '0006_auto_20200715_1532'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='usergroup',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='lovematch.UserGroup'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='answer',
            unique_together={('question', 'usergroup')},
        ),
        migrations.RemoveField(
            model_name='answer',
            name='user',
        ),
    ]
